[program:b2c-admin-horizon]
process_name=%(program_name)s
command=php /var/www/liyukj/b2c/admin/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=laradock
redirect_stderr=true
stdout_logfile=/var/www/liyukj/b2c/admin/storage/logs/horizon.log
stopwaitsecs=3600
