[program:think-queue]
process_name=%(program_name)s
command=php /var/www/liyukj/yaohuit/yaohuitong_project/think queue:listen --timeout=60
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=laradock
redirect_stderr=true
stdout_logfile=/var/log/supervisor/think-queue.log
